
version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - esnetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      - es01
    networks:
      - esnetwork

  insurance-service:
    build:
      context: ./insurance-service/docker
    container_name: insurance-service
    ports:
      - "8080:8080"
    depends_on:
      - es01
    networks:
      - esnetwork

networks:
  esnetwork:
    driver: bridge
